version: '3.7'

services:
  builder:
    build:
      context: src/
    volumes:
      - src:/opt


  prod:
    build:
      context: app/ 
    volumes:
      - /var/lib/docker/volumes/07_src/_data/target:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"

volumes:
  src: