version: '3.7'

services:
  builder:
    build:
      context: src/
      dockerfile: Dockerfile-build
    volumes:
      - src:/opt


  prod:
    build:
      context: src/
      dockerfile: Dockerfile-prod
    volumes:
      - src:/usr/local/tomcat/webapps/

    ports:
      - "8080:8080"

volumes:
  src: