version: '3.7'

services:
  builder:
    image: maven
    build:
      context: src/
    volumes:
      - src:/opt


  prod:
    image: tomcat
    build:
      context: app/ 
    volumes:
      - type: volume
        source: src
        target: /usr/local/tomcat/webapps/
        volume:
          nocopy: true

    ports:
      - "8080:8080"

volumes:
  src: