version: '3.7'

services:
  builder:
    build:
      context: src/
    init: true
    volumes:
      - ./src:/opt/app/
    networks:
      - hw

  prod:
    build:
      context: app/ 
    volumes:
      - ./src/target:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    networks:
      - hw

networks:
  hw:
    driver: bridge