version: '3.7'

services:
  builder:
    build:
      context: src/
    volumes:
      - src:/opt


  prod:
    build:
      context: app1/ 
    volumes:
      - app:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"

volumes:
  src:
  app: