---
- name: build app
  hosts: build
  become: yes 
  
  tasks:
  - name: Ensure docker is present
    apt:
      name: docker.io
      state: present

  - name: Create git container
    docker_container:
      name: git
      state: started
      image: bitnami/git:latest
      volumes:
        - app_dir:/tmp
      command:
        - git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
        - cp -r ./boxfuse-sample-java-war-hello/* /tmp