---
- name: build app
  hosts: build
  become: yes
  
  tasks:
  - name: Run apt upgrade
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Upgrade all packages on servers
    apt: 
      upgrade: full
      force_apt_get: yes     

  - name: Install java
    apt:
      name: default-jdk
      state: present

  - name: Install maven
    apt:
      name: maven
      state: present

  - name: Install git
    apt:
      name: git
      state: present

  - name: Install docker
    apt:
      name: docker.io
      state: present  

  - name: purge /tmp
    file:
      path: /tmp/boxfuse-sample-java-war-hello
      state: absent

  - name: git clone boxfuse
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    args:
      chdir: /tmp
   
  - name: build a war
    command: mvn package
    args:
      chdir: /tmp/boxfuse-sample-java-war-hello/

  - name: drop a docker file
    synchronize:
      src: ./Dockerfile
      dest: /tmp/Dockerfile

  - name: Build an image and push it to dockerhub
    docker_image:
      build:
        path: /tmp
      name: hw-09
      repository: artpanda/hw-09
      push: yes
      source: build

- name: start on prod
  hosts: prod
  become: yes

  tasks:
  - name: Run apt upgrade
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Upgrade all packages on servers
    apt: 
      upgrade: full
      force_apt_get: yes 

  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Start a container
    docker_container:
      name: hw-09
      state: started
      image: "artpanda/hw-09:latest"
      pull: true
      ports:
        - "8080:8080"