---
- name: build
  hosts: prod
  become: yes
  
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /usr/share/nginx/html/index.html
      regexp: 'Welcome to nginx'
      line: <p><script> document.write(new Date().toLocaleDateString()); </script></p>

  - name: ensure nginx
    service:
      name: nginx
      state: started
    