---
- name: build app
  hosts: build
  become: yes 
  
  tasks: 
  - name: Ensure docker is present
    apt:
      name: docker.io
      state: present

  - name: Create git container
    docker_container:
      name: git
      state: started
      image: ubuntu:latest
      detach : false
      volumes:
        - app_dir:/opt
      command:
        -c apt-get install git -y
        -c git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
        -c mv ./boxfuse-sample-java-war-hello/ /opt
    register: docker_container_output

  - name: Show test output
    debug:
      msg: "{{ docker_container_output.ansible_facts.docker_container.Output }}"