---
- name: build app
  hosts: build
  become: yes
  
  tasks:
  - name: Install java
    apt:
      name: default-jdk
      state: present

  - name: Install maven
    apt:
      name: maven
      state: present

  - name: Install git
    apt:
      name: git
      state: present

  - name: git clone boxfuse
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    args:
      chdir: /tmp

  - name: build a war
    ccommand: mvn package
    args:
      chdir: /tmp/boxfuse-sample-java-war-hello

  - name: copy war file to ansible master
    ansible.builtin.fetch:
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/
  
- name: start app on prod
  hosts: prod
  become: yes

  tasks:   
  - name: isntall tomcat
    apt:
      name: tomcat9
      state: present

  - name: copy app from ansible master to prod
    ansible.builtin.copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
        owner: root
        group: root
        mode: '0777'

  - name: ensure tomcat is running
    service:
      name: tomcat9
      state: started
    